---
abstract: 'Import source for Russian values in Project Nebraska database'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: NX-Nebraska-Import-Source-GKS
no_index:
  directory:
    - inc
    - t
requires:
  NX::Nebraska: 0.05
  Spreadsheet::ParseExcel: 0
  perl: 5.10.0
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: 0.01
